pluginManagement { repositories { gradlePluginPortal(); maven { url = 'https://maven.fabricmc.net/' } } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.PREFER_PROJECT); repositories { mavenCentral(); maven { url = 'https://maven.fabricmc.net/' } } }
rootProject.name = 'donutsmp-observer'
